# https://docs.zizmor.sh/configuration
rules:
  ref-version-mismatch:
    disable: true
  undocumented-permissions:
    disable: true
  anonymous-definition:
    disable: true
  concurrency-limits:
    disable: true
